default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
        exclude: docs/mkdocs.yml
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=79]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: hooks
        additional_dependencies: [flake8-typing-imports==1.9.0]
        args: # arguments to configure flake8
            # making isort line length compatible with black
            - "--max-line-length=120"
